package rules;

import com.sbnz.model.models.Banknote;
import com.sbnz.model.models.FactConclusion;
import com.sbnz.model.enums.InputFeatures;
import com.sbnz.model.enums.DerivedStatus;


// Pravilo 1
rule "Global Status - COLLECTOR_GRADE"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(paperStatus == DerivedStatus.PaperStatus.PREMIUM, foldingLevel == DerivedStatus.FoldingLevel.NO_FOLDS, integrity == DerivedStatus.Integrity.INTACT, cleanliness == DerivedStatus.Cleanliness.IMMACULATE, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.COLLECTOR_GRADE) };
end

// Pravilo 2
rule "Global Status - EXCELLENT_CONDITION (Minimal Folds)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(foldingLevel == DerivedStatus.FoldingLevel.MINIMAL_FOLDS, integrity == DerivedStatus.Integrity.INTACT, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.EXCELLENT_CONDITION) };
end

// Pravilo 3
rule "Global Status - EXCELLENT_CONDITION (Lightly Folded)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(foldingLevel == DerivedStatus.FoldingLevel.LIGHTLY_FOLDED, integrity == DerivedStatus.Integrity.INTACT, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.EXCELLENT_CONDITION) };
end

// Pravilo 4
rule "Global Status - CIRCULATED (Strong Paper)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(paperStatus == DerivedStatus.PaperStatus.STRONG, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.CIRCULATED) };
end

// Pravilo 5
rule "Global Status - CIRCULATED (Heavily Folded)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(foldingLevel == DerivedStatus.FoldingLevel.HEAVILY_FOLDED, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.CIRCULATED) };
end

// Pravilo 6
rule "Global Status - POOR_CONDITION (Degraded Paper)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(paperStatus == DerivedStatus.PaperStatus.DEGRADED, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.POOR_CONDITION) };
end

// Pravilo 7
rule "Global Status - POOR_CONDITION (Contaminated)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(cleanliness == DerivedStatus.Cleanliness.CONTAMINATED, globalStatus == null)
    then
        modify($fc) { setGlobalStatus(DerivedStatus.GlobalStatus.POOR_CONDITION) };
end

// Pravilo 8
rule "Grade Limit - MAX_VERY_GOOD (Moderate Damage)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(integrity == DerivedStatus.Integrity.MODERATE_DAMAGE, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_VERY_GOOD) };
end

// Pravilo 9
rule "Grade Limit - MAX_VERY_GOOD (Rounded Corners)"
    agenda-group "global-status-limits"
    when
        $b: Banknote($id: id, corners == InputFeatures.Corners.ROUNDED_OR_MISSING)
        $fc: FactConclusion(banknoteId == $id, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_VERY_GOOD) };
end

// Pravilo 10
rule "Grade Limit - MAX_FAIR (Severe Damage)"
    agenda-group "global-status-limits"
    when
        $fc: FactConclusion(integrity == DerivedStatus.Integrity.SEVERE_DAMAGE, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_FAIR) };
end

// Pravilo 11
rule "Grade Limit - MAX_FAIR (Damaged Paper)"
    agenda-group "global-status-limits"
    when
        $b: Banknote($id: id, wear == InputFeatures.Wear.DAMAGED_PAPER)
        $fc: FactConclusion(banknoteId == $id, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_FAIR) };
end

// Pravilo 12
rule "Grade Limit - MAX_VERY_FINE (Foil Broken Surface)"
    agenda-group "global-status-limits"
    when
        $b: Banknote($id: id, foilFeatures == InputFeatures.FoilFeatures.DAMAGED_FOLDS_BROKEN_SURFACE)
        $fc: FactConclusion(banknoteId == $id, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_VERY_FINE) };
end

// Pravilo 13
rule "Grade Limit - MAX_VERY_FINE (Foil Significantly Damaged)"
    agenda-group "global-status-limits"
    when
        $b: Banknote($id: id, foilFeatures == InputFeatures.FoilFeatures.SIGNIFICANTLY_DAMAGED)
        $fc: FactConclusion(banknoteId == $id, gradeLimit == null)
    then
        modify($fc) { setGradeLimit(DerivedStatus.GradeLimit.MAX_VERY_FINE) };
end